name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI]')"
    steps:
      - uses: actions/checkout@v2

      - name: Increment cache version
        run: |
          sed -i -r 's/(.*)(\CACHE_VERSION = )([0-9]+)(.*)/echo "\1\2$((\3+1))\4"/ge' "${GITHUB_WORKSPACE}/pwa/sw_content.js"
          git config --global user.email "internet-site@outlook.com"
          git config --global user.name "CI"
          git add ${GITHUB_WORKSPACE}/pwa/sw_content.js
          git commit -m "[CI] Increment cache version"
          git push     
